### ISSUE TITLE
Doesn't handle line continuations

### ISSUE THREAD

**Issue by JerseyTechGuy** [RonenNess/sini#2]
With real world INIs this does not handle line continuations ||+

**Comment by RonenNess** [comment]
Hello, 

What do you mean line continuation with `||+`? The line ends with double pipe and a plus to continue next line?
Can you show me example of that usage?

Currently SINI support changing continuation character but only one character.

Thanks

**Comment by JerseyTechGuy** [comment]
Yes, this line continuation is handled by windows natively. We have used this in INIs for many decades. For example, this would be read ad the full value for SQL:
  

  
SQL=SELECT * FROM mytable ||+
  
WHERE myfield = ‘blah’ ||+
  
ORDER BY myotherfield DESC
  
  
  
  
  
  
  

  
  
>

**Comment by RonenNess** [comment]
Cool, never seen it before. Guess it won't be too hard to change the continuation character with a string and then you'll be able to change it via the config.

I'll try to push this change sometime soon when I'll have some dead time, but no promises :)

**Comment by RonenNess** [comment]
Done, check out last version.
If there are any issues reopen this.

Thanks!
