### ISSUE TITLE
Doesn't handle Section names with spaces

### ISSUE THREAD

**Issue by JerseyTechGuy** [RonenNess/sini#3]
In the real world INI sections can have spaces.  RegEx fails when the section is [My Section] for example

**Comment by RonenNess** [comment]
TBH I have never seen an INI section with spaces, its always with dot, dashes, underscore etc.. (and it doesn't really have a unified standard to go by)..

But you can change the regex validator like this:

```cs
var config = IniConfig.CreateDefaults();
config.KeyValidationRegex = @"^[a-zA-Z_\.0-9 ]+$";
var ini = new IniFile("your_ini_file.ini", config);
```

To allow sections with spaces.
Hope this helps!

Edit: just keep in mind converting INI to objects won't work like this.
