### ISSUE TITLE
Non-bool values not parsing

### ISSUE THREAD

**Issue by kswanner** [RonenNess/sini#4]
I am having an issue with parsing non-boolean values (yes, no, etc.) into a bool.

`[Extra]
Hospital=1234
SessionType=12
SessionDate=3/1/2021
SessionEmail=xxx@yyy.com
SessionPhone=512-555-1212
SessionAccessible=yes
Language=E
`
`public class Extra
{
	public string Hospital { get; set; }
	public string SessionType { get; set; }
	public string SessionDate { get; set; }
	public string SessionEmail { get; set; }
	public string SessionPhone { get; set; }
	public bool SessionAccessible { get; set; }
	public string Language { get; set; }

	public Extra()
	{
		Hospital = "";
		SessionType = "";
		SessionDate = "";
		SessionEmail = "";
		SessionPhone = "";
		SessionAccessible = false;
		Language = "";
	}
}
`
When I read the ini file, Sini throws an exception at IniFile.cs:425. It doesn't get into GetBool to convert the non-bool value. Valid bool values (true and false) are still parsed correctly. I've looked at the IniFile.DefaultConfig.BoolPositiveValues and IniFile.DefaultConfig.BoolNegativeValues and the values mentioned in the documentation are there--the code just doesn't get to use them.

This is not an urgent issue since valid bool values work. But, it would be nice to be able to use the non-bool values.

**Comment by RonenNess** [comment]
Hi,
Thank you for letting me know, just released a version that hopefully fix it (and upgrade .net to 7).
If problem persist please reopen this issue.

Thanks! :)

**Comment by kswanner** [comment]
Looks like it's working now. Thanks!
